export const SET_MEAL_TYPE = 'SET_MEAL_TYPE';
export const SET_TOTAL_CALORIES = 'SET_TOTAL_CALORIES';
export const SET_TOTAL_MEALS_PER_DAY = 'SET_TOTAL_MEALS_PER_DAY';
export const SET_CALORIE_SPREAD = 'SET_CALORIE_SPREAD';
export const SET_CURRENT_UNIT = 'SET_CURRENT_UNIT';
export const SET_IS_LOADING= 'SET_IS_LOADING';